import type { Metadata } from "next";
import Link from "next/link";
import { capabilities, education, experience, professionalProjects, siteLinks } from "@/lib/site-data";

export const metadata: Metadata = { title: "About Samuel Owhondah | Psami", description: "The experience and approach behind Samuel Owhondah's product engineering, frontend systems and applied experiments." };

export default function AboutPage() {
  return <main id="main-content" className="site-container inner-page">
    <div className="page-overline"><span>04 / PERSON</span><Link href="/">← Index</Link></div>
    <header className="inner-hero"><p className="micro-label">About / Samuel Owhondah</p><h1>Building with clarity,<br/><em>from idea to system.</em></h1><p>I&apos;m a software engineer based in Northampton, UK. I work across product engineering, frontend systems and applied experimentation, with an interest in making complex things feel clear.</p></header>
    <section className="inner-section"><div className="section-intro"><span className="section-number">01 / PRACTICE</span><h2>How I work.</h2></div><div className="inner-copy"><p>My work has moved between data-rich React interfaces, real-time product features, Python services, third-party integrations and the infrastructure that gets them into users&apos; hands.</p><p>An earlier foundation in Electrical and Electronics Engineering still shapes how I think: understand the system, find the signal and make the whole thing easier to reason about.</p></div></section>
    <section className="inner-section"><div className="section-intro"><span className="section-number">02 / EXPERIENCE</span><h2>Where I&apos;ve worked.</h2></div><div className="record-list">{experience.map((item, index) => <article className="record" key={item.company}><span className="index-number">{String(index + 1).padStart(2, "0")}</span><div><h3>{item.company}</h3><p>{item.role} · {item.location}</p><p className="record-summary">{item.summary}</p><details><summary>Selected contributions <span>+</span></summary><ul>{item.contributions.map((contribution) => <li key={contribution}>{contribution}</li>)}</ul></details></div></article>)}</div></section>
    <section className="inner-section"><div className="section-intro"><span className="section-number">03 / CLIENT WORK</span><h2>Professional work.</h2></div><div className="record-list">{professionalProjects.map((item, index) => <article className="record" key={item.id}><span className="index-number">{String(index + 1).padStart(2, "0")}</span><div><h3>{item.name}</h3><p>{item.category} · {item.role}</p><p className="record-summary">{item.summary}</p><details><summary>More context <span>+</span></summary><p>{item.focus}</p><p>{item.technologies.join(" · ")}</p>{item.liveUrl && <a href={item.liveUrl} target="_blank" rel="noreferrer">Visit site ↗</a>}</details></div></article>)}</div></section>
    <section className="inner-section"><div className="section-intro"><span className="section-number">04 / BACKGROUND</span><h2>Education & tools.</h2></div><div className="inner-copy"><div className="education-list">{education.map((item) => <div key={item.degree}><strong>{item.degree}</strong><span>{item.school} · {item.location}</span></div>)}</div><details className="tools-details"><summary>Tools I work with <span>+</span></summary><ul>{capabilities.map((item) => <li key={item.title}><strong>{item.title}</strong><span>{item.technologies.join(" · ")}</span></li>)}</ul></details></div></section>
    <section className="inner-section contact-section"><div className="section-intro"><span className="section-number">05 / CONTACT</span><h2>In touch.</h2></div><div className="inner-copy"><p>Open to selected engineering roles and product collaborations.</p><div className="about-contact"><a href={siteLinks.email}>Email ↗</a><a href={siteLinks.github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={siteLinks.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href={siteLinks.resume} download>Résumé ↓</a></div></div></section>
  </main>;
}
